apiVersion: v2
name: rekor
description: Part of the sigstore project, Rekor is a timestamping server and transparency log for storing signatures, as well as an API based server for validation

type: application

version: 1.3.13
appVersion: 1.3.2

keywords:
  - security
  - transparency logs

home: https://sigstore.dev/
sources:
  - https://github.com/sigstore/rekor
maintainers:
  - name: The Sigstore Authors

dependencies:
  - name: trillian
    version: 0.2.16
    repository: https://sigstore.github.io/helm-charts
    condition: trillian.enabled

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: createtree
      image: ghcr.io/sigstore/scaffolding/createtree:v0.6.9@sha256:acd6f2bc2ad9bac400f86fc08d7c1042e0727fe6d0360a36b958ca25208d627a
    - name: curlimages/curl
      image: docker.io/curlimages/curl:8.4.0@sha256:4a3396ae573c44932d06ba33f8696db4429c419da87cbdc82965ee96a37dd0af
    - name: rekor-server
      image: gcr.io/projectsigstore/rekor-server:v1.3.2@sha256:82ae401d5a34754b27cab1b2b4530451048cb320cc8c2e33952156d8bc0f6124
    - name: redis
      image: docker.io/redis:6.2.13-alpine3.18@sha256:e582909983ce92291977d864b5a7b2a46bee680c2e515bd12c0ab3415a410b33
    - name: backfill-redis
      image: ghcr.io/sigstore/rekor/backfill-redis:v1.3.2@sha256:f7cdad65d7b25eac4521cb0072ac9e3a015af8326c578c10961733abd53d12c7
